enabled: true

buildpack:
  host: git.hubteam.com
  organization: HubSpotProtected
  repository: Blazar-Buildpack-Java
  branch: v2-single-module

env:
  SKIP_VERSION_OVERRIDE_ON_BRANCH: 2.5.6-hubspot-generic-inherit
